name: Test Workflow

on:
  push:
    branches: ["test"]
  workflow_dispatch:
jobs:
  pip-build:
    runs-on: ubuntu-latest
    name: Build Python Packages
    env:
      WATCH_FILE_PATTERNS: |
        **/requirements.txt
        **.py    
